### ISSUE TITLE
pycallgraph

### ISSUE THREAD

**Issue by mmesiti** [edbennett/high-performance-python#9]
- make sure that it is clear that the `pycallgraph` example need to run on the cluster and not on the personal machine (hope I did not get it the other way around)
- `pycallgraph` called as a program does not seem to work anymore (shouldn't one use `pycallgraph3` instead?)

**Comment by edbennett** [comment]
removed this section entirely as the project is unmaintained and nonfunctional, and there is no obvious alternative
